### ISSUE TITLE
Browse Repositories not availabe using Atto or TinyMCE editors

### ISSUE THREAD

**Issue by jh1991** [catalyst/moodle-local_sitenotice#18]
When creating a Site notice, after clicking the button to insert an image, the "browse repositories..." (Atto) or "Find or upload an image..." (TinyMCE) option is not available. It is still possible to embed an image that is hosted externally.

Normal Atto Editor:
![normal atto](https://user-images.githubusercontent.com/41098576/153309096-c0d803a8-2e52-4921-954b-40248eca8d3f.png)

Site Notice Atto Editor:
![site notice atto](https://user-images.githubusercontent.com/41098576/153309110-5234a5a2-c016-499f-89a2-52ede33c9e6b.png)

Normal TinyMCE Editor:
![normal tiny](https://user-images.githubusercontent.com/41098576/153309126-2814c827-1ee6-4733-8c1d-69f831c63cb7.png)

Site Notice TinyMCE Editor:
![site notice tiny](https://user-images.githubusercontent.com/41098576/153309133-47b95562-7d62-4dfe-8fa5-e197a23b80ab.png)
.

**Comment by dmitriim** [comment]
OK. Changing this from a bug to enhancement as this part of functionality hasn't been implemented.
