### ISSUE TITLE
Incorporating some features of your "Broadcast" plugin

### ISSUE THREAD

**Issue by acquaalta** [catalyst/moodle-local_sitenotice#36]
Hi,
You developed almost a similar plugin called "Broadcast" which has the following features that "Site Notice" doesn't:

- [ ]  Additional scopes - Site/Category/Course/Dashboard
- [x]  Active/Expiry dates
- [ ] The ability to choose if the notice would be presented only to logged-in users
- [ ] Type of notification (Modal, Bootstrap notification)

It would be great if you could consider adding these features to "Site Notice".
And yeah, I know that adding Category/Course scopes would be in contrast to the idea of "**_Site_** Notice", but it already supports cohorts which are already under the site level :-)

"Broadcast" plugin link:
https://github.com/catalyst/moodle-tool_broadcast

Thanks

**Comment by dmitriim** [comment]
hi @acquaalta 
Thanks for raising this. We will discuss this internally.

**Comment by dmitriim** [comment]
We have decided to merge the plugins and retire  https://github.com/catalyst/moodle-tool_broadcast 
Please feel  free to help us with that by providing a patch or sponsor this work (you can contact our sales team on https://catalyst-au.net/contact-us)

**Comment by dmitriim** [comment]
Active/Expiry dates added.

**Comment by acquaalta** [comment]
Thanks a lot. I would continue to dream about the other features and maybe one day it would happen :-)

**Comment by dmitriim** [comment]
I have split this one to issues so they can be attacked separately:
- https://github.com/catalyst/moodle-local_sitenotice/issues/61 
- https://github.com/catalyst/moodle-local_sitenotice/issues/62
- https://github.com/catalyst/moodle-local_sitenotice/issues/63

Will close this one.
