### ISSUE TITLE
Hardcoded lang strings

### ISSUE THREAD

**Issue by dinism** [catalyst/moodle-local_sitenotice#37]
I'm a PT-PT translator.
**When editing notice settings:**
![imagem](https://user-images.githubusercontent.com/14828021/160235007-ab1ce645-8a89-40b4-aecd-d172926b3acc.png)
**When i preview a notice:**
**![imagem](https://user-images.githubusercontent.com/14828021/160235032-b7194567-3787-4c49-83ab-dc93ac718dc9.png)
When a notice is shown:**
![imagem](https://user-images.githubusercontent.com/14828021/160235072-ec78a6fd-18de-4985-bee1-07c3bc0fbb90.png)

**Comment by dmitriim** [comment]
Good catch @dinism !
Please feel free to submit a patch to fix all those hard-coded strings.

**Comment by cameron1729** [comment]
Hi @dinism, I've sent a patch to fix those strings you pointed out.

Just mentioning that the close/accept buttons do appear to be language strings in the most recent version of the plugin. The relevant keys are:

- button:accept
- button:close

Cheers.
