### ISSUE TITLE
User is able to access site without accepting a notice

### ISSUE THREAD

**Issue by brankovukasovic** [catalyst/moodle-local_sitenotice#58]
Steps to reproduce:

1. Create a notice with Requires acknowledgement set to Yes.
2. User logs in to the site.
3. The notice is displayed.
4. User closes the notice, without accepting the notice (the “I have read and understand the notice (closing this notice will log you off this site).” checkbox left unchecked)
5. User is logged out automatically
6. Then, the same user logs in again.

**Expected result:**
The notice should be displayed again, and user has to accept it to be able to use the site (I guess).

**Actual result:**
User can access the site without having to accept the notice.

**Comment by dmitriim** [comment]
Hi @brankovukasovic! Thanks for reporting this. I was able to replicate the issue. Marking it as a bug

**Comment by dmitriim** [comment]
This has been fixed
