### ISSUE TITLE
PHP 8 - Unable to read from Database Error

### ISSUE THREAD

**Issue by katcher** [catalyst/moodle-local_sitenotice#65]
Moodle 4.1
PHP 8.1

the comparison function string and integer has been changed in php 8.x

Prior to PHP 8.0.0, if a string is compared to a number or a numeric string then the string was converted to a number before performing the comparison. 

https://www.php.net/manual/en/language.operators.comparison.php

Causes comparison if($column > 0) to fail

/**
     * Process hyperlink counts.
     *
     *** @param int $column column**
     * @param \stdClass $row rows
     *
     * @return string|null
     */
    public function other_cols($column, $row) {
        // Check if the column name is the id of a notice hyperlink.
        if ($column > 0) {
            // Only do link count on the first record of a user.
            if ($this->previoususer == $row->userid) {
                return '';
            }
            $linkcounts = linkhistory::count_clicked_links($row->userid, $row->noticeid, $column);
            if (isset($linkcounts[$column])) {
                return $linkcounts[$column]->count;
            } else {
                return '0';
            }
        } else {
            return null;
        }
    }

Error reading from database

[More information about this error](https://docs.moodle.org/401/en/error/moodle/dmlreadexception)

Debug info: ERROR: invalid input syntax for type bigint: "noticetitle"
CONTEXT: unnamed portal parameter $3 = '...'
SELECT h.hlinkid, l.text, l.link, COUNT(h.hlinkid)
FROM mdl_local_sitenotice_hlinks_his h
JOIN mdl_local_sitenotice_hlinks l on h.hlinkid = l.id
WHERE h.userid = $1 AND l.noticeid = $2 AND h.hlinkid = $3
GROUP BY h.hlinkid, l.text, l.link
-- line 89 of /local/sitenotice/classes/persistent/linkhistory.php: call to pgsql_native_moodle_database->get_records_sql()
-- line 280 of /local/sitenotice/classes/table/acknowledged_notice.php: call to local_sitenotice\persistent\linkhistory::count_clicked_links()
-- line 834 of /lib/tablelib.php: call to local_sitenotice\table\acknowledged_notice->other_cols()
-- line 2022 of /lib/tablelib.php: call to flexible_table->format_row()
-- line 2146 of /lib/tablelib.php: call to table_sql->build_table()
-- line 54 of /local/sitenotice/renderer.php: call to table_sql->out()
-- line 495 of /lib/outputrenderers.php: call to local_sitenotice_renderer->render_acknowledged_notice()
-- line 73 of /local/sitenotice/report/acknowledged_report.php: call to plugin_renderer_base->render()
[array (
0 => '55',
1 => '3',
2 => 'noticetitle',
)]
Error code: dmlreadexception×Dismiss this notification
Stack trace:
line 494 of /lib/dml/moodle_database.php: dml_read_exception thrown
line 293 of /lib/dml/moodle_read_slave_trait.php: call to moodle_database->query_end()
line 341 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->read_slave_query_end()
line 1027 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
line 89 of /local/sitenotice/classes/persistent/linkhistory.php: call to pgsql_native_moodle_database->get_records_sql()
line 280 of /local/sitenotice/classes/table/acknowledged_notice.php: call to local_sitenotice\persistent\linkhistory::count_clicked_links()
line 834 of /lib/tablelib.php: call to local_sitenotice\table\acknowledged_notice->other_cols()
line 2022 of /lib/tablelib.php: call to flexible_table->format_row()
line 2146 of /lib/tablelib.php: call to table_sql->build_table()
line 54 of /local/sitenotice/renderer.php: call to table_sql->out()
line 495 of /lib/outputrenderers.php: call to local_sitenotice_renderer->render_acknowledged_notice()
line 73 of /local/sitenotice/report/acknowledged_report.php: call to plugin_renderer_base->render()

**Comment by dmitriim** [comment]
thanks @katcher for reporting a bug in PHP 8.0. PR is always welcome.

**Comment by petersistrom** [comment]
Hi @dmitriim we ran into this error with one of our clients, so I've added the fix mentioned here https://github.com/catalyst/moodle-local_sitenotice/pull/69#discussion_r1430952940.  I figured a new [401](https://github.com/catalyst/moodle-local_sitenotice/commits/MOODLE_401_STABLE-issue-65/) branch was the cleanest. If you could have a look at it when you get a chance, the we can move it to MOODLE_401_STABLE when it looks good?

**Comment by dmitriim** [comment]
Hi @petersistrom 
Is it the issue with php 8.1 or something else? AFAIK Moodle 4.1 still supports php 7.4 so branch MOODLE_401_STABLE should support it as well.

**Comment by petersistrom** [comment]
Hi @dmitriim yes looks like it's an issue with php 8.1

**Comment by dmitriim** [comment]
I believe the proper fix for the current issue should be adding type-hinting through the code  as per https://github.com/catalyst/moodle-local_sitenotice/issues/70 That should be supported by php 7.4+

**Comment by dmitriim** [comment]
This should be fixed in the latest version of the plugin.
