### ISSUE TITLE
Two issues

### ISSUE THREAD

**Issue by jimenez-b** [catalyst/moodle-local_sitenotice#66]
Hello, we're testing your plugin and ran into an error while trying to download the results of a notice:
Default exception handler: Exception - Call to undefined method local_sitenotice\\helper::retrieve_notice_links() Debug: \n
Error code: generalexceptionmessage\n* line 107 of /local/sitenotice/classes/table/acknowledged_notice.php: Error thrown\n* line 87 of /local/sitenotice/classes/table/acknowledged_notice.php: call to local_sitenotice\\table\\acknowledged_notice->define_table_columns()\n* line 61 of /local/sitenotice/report/acknowledged_report.php: call to local_sitenotice\\table\\acknowledged_notice->__construct()\n, referer: https://moodle4-dev.concordia.ca/local/sitenotice/report/acknowledged_report.php?noticeid=4&page=2

We found out that the helper doesn't exists on the appropriate class and if we comment out lines 106-109 it kinda works but still the functionality is missing out that part.
---------------------------
Also, we ran into a small warning 
PHP Warning:  Attempt to read property "id" on bool in /public/home/local/sitenotice/report/acknowledged_report.php on line 61

again, we changed line 61 to go from $notice->id to use $noticeid on line 34, and the warning it's removed.

**Comment by jimenez-b** [comment]
Moodle 4.1.3+
PHP 8.1.18

**Comment by dmitriim** [comment]
@cameron1729  FYI Moodle 4.1.3

**Comment by dmitriim** [comment]
This should be fixed in the latest version of the plugin.
